### ISSUE TITLE
A problem occurred configuring project ':ble_peripheral'.

### ISSUE THREAD

**Issue by runoob-coder** [rohitsangwan01/ble_peripheral#17]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':ble_peripheral'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 916ms
Error: Gradle task assembleDebug failed with exit code 1
After running the command /usr/bin/arch -arm64e xcrun devicectl list devices --timeout 5 --json-output /var/folders/74/8cyr0zf523qgjf35kpylf0p40000gn/T/flutter_tools.fCCVNA/core_devices.YPEJ93/core_device_list.json the file
/var/folders/74/8cyr0zf523qgjf35kpylf0p40000gn/T/flutter_tools.fCCVNA/core_devices.YPEJ93/core_device_list.json was expected to exist, but it did not.
The process exited with code 0 and
Stdout:

Devices:
Name                  Hostname                                     Identifier                             State                Model                 
-------------------   ------------------------------------------   ------------------------------------   ------------------   ----------------------
noob-coder的iPhone12   00008101-001624C20145001E.coredevice.local   1B18B11F-6BC0-4374-A34E-1501DECAE03F   available (paired)   iPhone 12 (iPhone13,2)

Stderr:

ERROR: Error writing JSON results: The file “core_device_list.json” doesn’t exist. (NSCocoaErrorDomain error 4 (0x04))
       NSURL = file:///var/folders/74/8cyr0zf523qgjf35kpylf0p40000gn/T/flutter_tools.fCCVNA/core_devices.YPEJ93/core_device_list.json
       NSFilePath = /var/folders/74/8cyr0zf523qgjf35kpylf0p40000gn/T/flutter_tools.fCCVNA/core_devices.YPEJ93/core_device_list.json
       ----------------------------------------
           The operation couldn’t be completed. No such file or directory (NSPOSIXErrorDomain error 2 (0x02))
After running the command /usr/bin/arch -arm64e xcrun devicectl list devices --timeout 5 --json-output /var/folders/74/8cyr0zf523qgjf35kpylf0p40000gn/T/flutter_tools.fCCVNA/core_devices.HqKjhC/core_device_list.json the file
/var/folders/74/8cyr0zf523qgjf35kpylf0p40000gn/T/flutter_tools.fCCVNA/core_devices.HqKjhC/core_device_list.json was expected to exist, but it did not.
The process exited with code 0 and
Stdout:

Devices:
Name                  Hostname                                     Identifier                             State                Model                 
-------------------   ------------------------------------------   ------------------------------------   ------------------   ----------------------
noob-coder的iPhone12   00008101-001624C20145001E.coredevice.local   1B18B11F-6BC0-4374-A34E-1501DECAE03F   available (paired)   iPhone 12 (iPhone13,2)

Stderr:

ERROR: Error writing JSON results: The file “core_device_list.json” doesn’t exist. (NSCocoaErrorDomain error 4 (0x04))
       NSURL = file:///var/folders/74/8cyr0zf523qgjf35kpylf0p40000gn/T/flutter_tools.fCCVNA/core_devices.HqKjhC/core_device_list.json
       NSFilePath = /var/folders/74/8cyr0zf523qgjf35kpylf0p40000gn/T/flutter_tools.fCCVNA/core_devices.HqKjhC/core_device_list.json
       ----------------------------------------
           The operation couldn’t be completed. No such file or directory (NSPOSIXErrorDomain error 2 (0x02))

**Comment by rohitsangwan01** [comment]
@runoob-coder have you upgraded your android AGP version ?

**Comment by runoob-coder** [comment]
@rohitsangwan01 

I am using gradle-8.3，do I need to upgrade？

**Comment by rohitsangwan01** [comment]
@runoob-coder i think i have to update my plugin to support AGP 8+
basically a small change, we need to include namespace in gradle of plugin, if you want you can gave it a try and raise Pr

**Comment by Yolo-cell-hash** [comment]
Facing a similar issue as @runoob-coder ...

**Comment by rohitsangwan01** [comment]
Fixed in V2.3.3
