### ISSUE TITLE
GATT_WRITE_NOT_PERMITTED

### ISSUE THREAD

**Issue by itanvation** [rohitsangwan01/ble_peripheral#8]
I have given write and read permissions to descriptor still i am getting write not permitted

**Comment by rohitsangwan01** [comment]
@vishwaanv Are you on latest version ?
Which Platform?
Exactly which permission enum values you are using for descriptor ?

**Comment by itanvation** [comment]
@rohitsangwan01  yes i am on the latest version , i am using read and write permissions below is the desp
int read = 2;
int write = 8;
int notify = 16;
platform android 
final desp =
    BleDescriptor(uuid: Constants.CLIENT_CONFIG, permissions: [read, write]);

**Comment by rohitsangwan01** [comment]
@vishwaanv instead of using hardcoded numbers for permissions, you should use enums like this
https://github.com/rohitsangwan01/ble_peripheral/blob/main/example/lib/home_controller.dart#L97-L104
https://github.com/rohitsangwan01/ble_peripheral/blob/main/example/lib/home_controller.dart#L124-L147

**Comment by itanvation** [comment]
thank you for your response can you please return gatserver object(i want to write and notify server object) would be a create help  once again thank you so much awesome package btw

**Comment by rohitsangwan01** [comment]
> thank you for your response can you please return gatserver object(i want to write and notify server object) would be a create help  once again thank you so much awesome package btw

To write and notify, do this

Set listener for available devices


BlePeripheral.setBleCentralAvailabilityCallback((String deviceId,bool isAvailable) {
// save deviceId when isAvailable true, remove when false
});


Then to notify this device, call updateCharacteristic like this

https://github.com/rohitsangwan01/ble_peripheral/blob/main/example/lib/home_controller.dart#L150

**Comment by itanvation** [comment]
val stringList = listOf("Name", "realme6",)
                val  data = createByteArray(stringList)
                var  a = gattServer?.getService(UUID.fromString("69e318bc-1dd0-49b5-92"))?.getCharacteristic(
                    UUID.fromString("69e318be-1dd0-49b5-")).let {
                   it?.value = data
                    gattServer?.notifyCharacteristicChanged(device,it,false)

                }
                
                i am doing some thing like this so i nedd gattServer object if you could reurn gattserver object in intialize method  ??

**Comment by rohitsangwan01** [comment]
You can achieve this same thing by

await BlePeripheral.updateCharacteristic(
          deviceId: deviceId,
          characteristicId: 'Characteristic Id',
          value: utf8.encode("Test Data"),
        );

GattServer is android specific only
So we can't access that in flutter, because other platforms does not have this, so it will be hard to maintain cross-platform api

**Comment by itanvation** [comment]
thanks for the reply
